scenario,status,details,timestamp
basic_data_to_server_setup,PASS,"{'mqtt_broker_enabled': True, 'mqtt_port_correct': True, 'mqtt_anonymous_enabled': True, 'mqtt_process_running': True, 'dts_enabled': True, 'period_correct': True, 'mqtt_server_correct': True, 'mqtt_topic_correct': True, 'mqtt_client_id_correct': True, 'mqtt_qos_correct': True, 'no_errors_in_logs': False, 'mqtt_message_received': True, 'raw_results': {'mqtt_enabled': ""mosquitto.mqtt.enabled='1'"", 'mqtt_port': ""mosquitto.mqtt.local_port='1883'"", 'mqtt_anonymous': ""mosquitto.mqtt.anonymous_access='1'"", 'mqtt_process': '9736 root      4708 S    /usr/sbin/mosquitto -c /tmp/mosquitto.conf', 'dts_instance': ""data_sender.1.name='NewInstance2'"", 'dts_enabled': ""data_sender.1.enabled='1'"", 'dts_period': ""data_sender.1.period='3'"", 'mqtt_server': ""data_sender.2.mqtt_host='test.mosquitto.org'"", 'mqtt_topic': ""data_sender.2.mqtt_topic='testing'"", 'mqtt_client_id': ""data_sender.2.mqtt_client_id='1'"", 'mqtt_qos': ""data_sender.2.mqtt_qos='1'"", 'log_errors': ""850 Thu Feb  6 09:31:07 2025 daemon.err data_sender: Failed to connect. Lookup error. (Will stop printing error messages due to log spam. That does not mean that the problem is no longer present!)\n857 Thu Feb  6 09:32:11 2025 daemon.err rms_mqtt[16097]: Failed to connect with authentication keys\n862 Thu Feb  6 09:32:45 2025 daemon.err data_sender: (NewInstance1_output) Failed to connect. Lookup error.\n863 Thu Feb  6 09:32:48 2025 daemon.err data_sender: Failed to connect. Lookup error.\n864 Thu Feb  6 09:32:51 2025 daemon.err data_sender: Failed to connect. Lookup error.\n865 Thu Feb  6 09:32:54 2025 daemon.err data_sender: Failed to connect. Lookup error.\n866 Thu Feb  6 09:32:57 2025 daemon.err data_sender: Failed to connect. Lookup error.\n869 Thu Feb  6 09:33:00 2025 daemon.err data_sender: Failed to connect. Lookup error. (Will stop printing error messages due to log spam. That does not mean that the problem is no longer present!)\n872 Thu Feb  6 09:33:16 2025 daemon.err data_sender: (NewInstance1_output) Failed to connect. Lookup error.\n874 Thu Feb  6 09:33:16 2025 daemon.err data_sender: [(null)] Error encountered getting input plugin '5' config\n875 Thu Feb  6 09:33:16 2025 daemon.err data_sender: Error while parsing config section '4'\n876 Thu Feb  6 09:33:19 2025 daemon.err data_sender: Failed to connect. Lookup error.\n877 Thu Feb  6 09:33:22 2025 daemon.err data_sender: Failed to connect. Lookup error.\n879 Thu Feb  6 09:33:25 2025 daemon.err data_sender: Failed to connect. Lookup error.\n881 Thu Feb  6 09:33:25 2025 daemon.err data_sender: (NewInstance1_output) Failed to connect. Lookup error.\n882 Thu Feb  6 09:33:28 2025 daemon.err data_sender: Failed to connect. Lookup error.\n883 Thu Feb  6 09:33:31 2025 daemon.err data_sender: Failed to connect. Lookup error.\n884 Thu Feb  6 09:33:34 2025 daemon.err data_sender: Failed to connect. Lookup error.\n888 Thu Feb  6 09:33:37 2025 daemon.err data_sender: Failed to connect. Lookup error.\n889 Thu Feb  6 09:33:40 2025 daemon.err data_sender: Failed to connect. Lookup error. (Will stop printing error messages due to log spam. That does not mean that the problem is no longer present!)"", 'mqtt_message': True}}",2025-02-06 09:49:08
